### ISSUE TITLE
Maintainer and Author field missing from Description File

### ISSUE THREAD

**Issue by zaid-golwala** [hadley/gtable#52]
Hi,
I am trying to use your code base to run a check for gtable installed on R on Ubuntu 15.04.
I get following error : 

+ R CMD check gtable
* using log directory ‘/home/jenkins/workspace/Rlang_gtable_Ubuntu15.04/gtable.Rcheck’
* using R version 3.2.3 (2015-12-10)
* using platform: powerpc64le-unknown-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘gtable/DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
* DONE

Can you please update the Description File

**Comment by hadley** [comment]
You need to build the package before checking it.
